@startuml
header Restaurant Diagram
footer Page %page% of %lastpage%
title "Manage Restaurant (PUT) with Authorization"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<authMiddleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:user" as UserDatabase


@enduml