@startuml
header Restaurant Diagram
footer Page %page% of %lastpage%
title "Manage Restaurant (PUT) with Authorization"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:auth" as routerAuth
participant "<<controllers>>\n:auth" as controllersAuth
participant "<<model>>\n:User" as modelUser
database "<<MongoDB>>\n:user" as UserDatabase

client->server ++:req.post('/auth)
server->routerAuth++:app.use('/register', register)
routerAuth->controllersAuth ++:register()
controllersAuth->modelUser ++: create(req.body)
modelUser ->UserDatabase ++: UserSchema
UserDatabase --> modelUser --: user
controllersAuth <-- modelUser --: user
controllersAuth->client --:response
@enduml