@startuml
header Reservation Diagram
footer Page %page% of %lastpage%
title "Manage Reservation (DELETE) with Authorization"

participant "Client" as client
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:reservations" as routerReservations
participant "<<authMiddleware>>\n:auth" as authMiddleware
participant "<<controllers>>\n:reservations" as controllersReservations
participant "<<model>>\n:Reservation" as modelReservation
database "<<MongoDB>>\n:reservations" as ReservationsDatabase

client->server ++:req.delete('/reservations/:id')
server->routerReservations ++:app.use('/reservations', reservations)
routerReservations->>authMiddleware ++:protect, authorize('admin', 'user')

alt Not Authorized
    authMiddleware->>client :Unauthorized or Protected
else Authorized
    authMiddleware->>routerReservations -- :
    routerReservations->controllersReservations ++:deleteReservation()
    controllersReservations->modelReservation ++:findByIdAndDelete(req.params.id,req.body)
    modelReservation ->ReservationsDatabase ++: ReservationSchema
    ReservationsDatabase --> modelReservation --: reservation
    controllersReservations <-- modelReservation --: reservation
    controllersReservations->client --:response
end



@enduml